.github/workflows: add user documentation workflow
adevinta/lava-docs pull request #1
Opened 2024-03-05 09:31 UTC by seilagamo

Add a workflow that creates the user documentation automatically using [mdBook](https://rust-lang.github.io/mdBook/) to build the static site.

2024-03-05 10:25 UTC, jroimartin requested changes

2024-03-05 10:25 UTC, jroimartin commented on book.toml
> +[book]
Add copyright notice.

2024-03-05 10:25 UTC, jroimartin commented on .gitignore
> +book
```suggestion
/book/
```

2024-03-05 10:25 UTC, jroimartin commented on .github/workflows/doc.yaml
> +  id-token: write
I would split the `build` job in 2 jobs: `build` and `deploy`. So, only `deploy` has the `pages: write` and `id-token: write` permissions. I would also add a comment explaining why these permissions are needed. Check file comment for more details.

2024-03-05 10:25 UTC, jroimartin commented on .github/workflows/doc.yaml
> +    - mdBook
Should we use `main` here? Check file comment for more details.

```suggestion
      - main
```

2024-03-05 10:25 UTC, jroimartin commented on .github/workflows/doc.yaml
I would rewrite the workflow to something like this. Check the other comments for more details.

```yaml
# Copyright 2024 Adevinta

name: Deploy Lava documentation to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued. However, do not cancel
# in-progress runs as we want to allow these production deployments to
# complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build documentation
        run: ./build.bash
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'book'

  deploy:
    needs: build
    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

2024-03-05 10:25 UTC, jroimartin commented on .github/workflows/doc.yaml
> +  cancel-in-progress: false
I would add a comment to explain why this is needed. Check file comment for more details.

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +check_status (){
```suggestion
check_status() {
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +fix_headers (){
```suggestion
fix_headers() {
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +add_main_header(){
```suggestion
add_main_header() {
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +	sed -i "1s/^/# ${header}\n/" ${file}
I think this is more elegant.

```suggestion
	sed -i "1i # ${header}" "${file}"
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +	sed -i "s/^#/##/" ${file}
```suggestion
	sed -i "s/^#/##/" "${file}"
```

2024-03-05 10:25 UTC, jroimartin commented on .github/workflows/doc.yaml
> +          LAVA_VERSION: latest
I think we should always build the documentation for the latest version of Lava. At the end of the day we are only providing documentation for the latest release.

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +}
I would install the latest Lava release.

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +# Install Lava.
I would remove this comment. The name of the function is self-explanatory.

```suggestion
# Install Lava.
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +	mkdir -p "${install_dir}"
I would move this out of this function and pass the install dir as a parameter of the function before calling it. Also I would generate a directory using `mktemp`.

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +  add_main_header ${file} ${header}
Fix indentation. Use tabs.

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +sudo chmod +x ${install_dir}/mdbook
Move to a function `install_mdbook` similar to `install_lava`. Also, move the mdbook version to an env var at the beginning of the script. Finally, I would download it with:

```
curl -LsSf "https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz -C "${install_dir}" mdbook
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +	mkdir -p ${dir}
```suggestion
	mkdir -p "$(dirname "${file}")"
```

2024-03-05 10:25 UTC, jroimartin commented on build.bash
> +  add_main_header ${file} ${header}
```suggestion
  ${install_dir}/lava help "${topic}" > "${file}"
  fix_headers "${file}"
  add_main_header "${file}" "${header}"
```

2024-03-05 10:25 UTC, jroimartin commented on src/README.md
> +
Remove empty line.

2024-03-05 10:27 UTC, jroimartin commented
BTW can we include the lava version used to generate the documentation in the site?

2024-03-05 11:09 UTC, seilagamo commented on .github/workflows/doc.yaml
> +    - mdBook
This is included in the last commit which means to be dropped before the merging. It's only to test the changes in this branch.

2024-03-06 10:54 UTC, jroimartin requested changes

2024-03-06 10:54 UTC, jroimartin commented on build.bash
> +	sudo chmod +x ${dir}/lava
I think you don't need sudo.

```suggestion
	chmod +x ${dir}/lava
```

2024-03-06 10:54 UTC, jroimartin commented on build.bash
> +	sudo chmod +x ${dir}/mdbook
I think you don't need sudo.

```suggestion
	chmod +x ${dir}/mdbook
```

2024-03-06 10:54 UTC, jroimartin commented on build.bash
>  	# Try to download a Lava release from GitHub.
I would remove this comment. Now there is only one download option.

```suggestion
```

2024-03-06 10:54 UTC, jroimartin commented on build.bash
> +	check_status $? "error: could not install mdBook"
I would follow the same logic you used in `install_lava`. You are already checking the status when calling `install_mdbook`. Also I'd rename the function to `install_mdbook` in lowercase.

```suggestion
        local dir=$1
        local url="https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        
        if (curl -LsSf "${url}" | tar -xz -C "${dir}" mdbook) 2> /dev/null; then
                return 0
        fi
```

2024-03-06 10:54 UTC, jroimartin commented on build.bash
> +fi
I would install mdbook just after installing lava. So both calls to `install_` are together and we fail soon if any of the dependencies is not available.

2024-03-06 10:54 UTC, jroimartin commented on build.bash
> +${install_dir}/lava version > "src/last_version.md"
As we discussed, I's try to move this info to the sidebar.

2024-03-06 11:03 UTC, jroimartin requested changes

2024-03-06 11:03 UTC, jroimartin commented on build.bash
> +
I would add `set -e -u` and remove all calls to `check_status`.

```suggestion

set -e -u

```

2024-03-06 11:03 UTC, jroimartin commented on build.bash
> +	fi
I would remove the comment and the if. `set -e` will capture the error.

```suggestion
	local dir=$1
	local url='https://github.com/adevinta/lava/releases/latest/download/lava_linux_amd64.tar.gz'
	curl -LsSf "${url}" | tar -xz -C "${dir}" lava) 2> /dev/null
```

2024-03-06 11:03 UTC, jroimartin commented on build.bash
> +fi
After adding `set -e` you can just call `install_lava`.

```suggestion
install_lava "${install_dir}
```

2024-03-06 11:44 UTC, jroimartin requested changes
LGTM. Clean up the commit history.

2024-03-06 12:09 UTC, jroimartin approved these changes

2024-03-06 12:11 UTC, merged