lava-docs: add controls section
adevinta/lava-docs pull request #4
Opened 2024-06-26 10:57 UTC by seilagamo

Add a section to describe controls and how to customize them.

2024-07-08 13:38 UTC, jroimartin requested changes

2024-07-08 13:38 UTC, jroimartin commented on .github/workflows/doc.yaml
> +      - '*'
Can't you do the following?

```yaml
on: [workflow_dispatch, push]
```

2024-07-08 13:38 UTC, jroimartin commented on src/README.md
> +Lava implements [here](controls.md).
```suggestion
catalog shipped with Vulcan.

The default Lava configuration covers the following security controls:

- DAST (Dynamic Application Security Testing)
- SAST (Static Application Security Testing)
- SCA (Software Composition Analysis)
- Secret detection

For more details, please visit the [Security controls](controls.md)
section of the documentation.
```

2024-07-08 13:38 UTC, jroimartin commented on build.bash
> +}
Why do you need this?

2024-07-08 13:38 UTC, jroimartin commented on src/specs/checktype_catalog.json
> +                "required": ["name", "description", "image", "timeout", "assets"],
Aren't the `description` and `timeout` fields optional?

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +same collection located at <https://github.com/adevinta/vulcan-checks>
```suggestion
same collection located at <https://github.com/adevinta/vulcan-checks>.
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +Behind the scenes Lava makes use of other security tools and custom security
```suggestion
Behind the scenes Lava uses other security tools and custom security
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +## Type of controls
```suggestion
## Types of security controls
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +
Remove extra newline.

```suggestion
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +covers.
```suggestion
The following table lists all the security controls covered by Lava's
default checktype collection.
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +| <div style="width:175px">Control</did> | Description
I would use mdbook's default style and rename the column to `Security Control`.

```suggestion
| Security Control | Description                                                                                                                                                         |
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +| Finding collection                     | This category referees to checktypes that do not run the analysis themselves. Instead, they collect the findings from 3rd party systems like Tenable.io or v
```suggestion
| Finding collection                     | This category refers to checktypes that do not run the analysis themselves. Instead, they collect the findings from 3rd party systems like Tenable.io or Vulners. |
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +| Data analysis                          | Checktypes focused on processing already available data to produce results from the point of view of information security.
```suggestion
| Data analysis                          | Checktypes focused on processing data sets to extract information considered relevant from an information security point of view.                                          |
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +| Checktype                                                                                                            | Description
```suggestion
| Checktype                                                                                                            | Description                                                                             | Security Control                     |
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +# Controls and customization
```suggestion
# Security Controls
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +## Enabled by Default
```suggestion
## Enabled by default
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +## Disabled by Default
```suggestion
## Disabled by default
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +      <th>Type of Control</th>
```suggestion
      <th>Security Control</th>
```

2024-07-08 13:38 UTC, jroimartin commented on src/controls.md
> +        >
I would use markdown tables and single-line descriptions. E.g.

```
Scan web addresses with projectdiscovery/nuclei. Official Documentation: <https://docs.projectdiscovery.io/tools/nuclei>.
```

2024-07-10 07:50 UTC, janelastur commented
Observations about the section of security controls.

- We should provide an order and sense of importance with the controls for the user lecture. An order of importance can be SAST --> SCA --> IAC --> Secret Detection --> DAST - Application --> rest of the controls not enabled by default. This should be the order because these are the ones enabled by default. So the first table "Types of controls" should be this list top to bottom. In the second table "Enabled by default", it should be from top to bottom SAST --> SCA --> IAC --> Secret Detection --> DAST - Application.
- "IaC" is its own category of control. It should be called "IaC" and not "SAST - IaC". This implies that there is only one type of SAST and it should be called "SAST" (and not "SAST - Application").
- In the "Type of controls - Description" Column we should standardise the format. Some of the descriptions is just the acronym, some are the acronym + an additional explanation and some are empty. In my opinion, all should have acronym + additional explanation.

2024-07-11 06:25 UTC, seilagamo commented
I do not agree with changing "SAST - IaC" with IaC because IaC (Infrastructure as Code) doesn't explain what kind of analysis the tool is performing. The definition of IaC is "the ability to provision and support your computing infrastructure using code instead of manual processes and settings" and is not a security control itself.

2024-07-11 08:37 UTC, jroimartin requested changes

2024-07-11 08:37 UTC, jroimartin commented on src/controls.md
> +| [vulcan-zap](https://github.com/adevinta/vulcan-checks/tree/master/cmd/vulcan-zap)           | Runs an OWASP ZAP passive or active scan. Official Documentation: <https://www.zaproxy.org/docs>
```suggestion
| [vulcan-zap](https://github.com/adevinta/vulcan-checks/tree/master/cmd/vulcan-zap)           | Runs an OWASP ZAP passive or active scan. Official Documentation: <https://www.zaproxy.org/docs>                                   | DAST - Application                |
```

2024-07-11 10:35 UTC, jroimartin requested changes
I added a couple of minor comments about the style. Please, fix them and clean-up the commit history. Also, delete the temporary changes in the workflow and the `build.bash` script.

2024-07-11 10:35 UTC, jroimartin commented on src/controls.md
> +| IaC Security       | Static analysis of Infrastructure as Code manifests. For instance, AWS CloudFormation templates or Terraform configurations.                                      |
For consistency with the other security controls.

```suggestion
| IaC Security       | Static analysis of Infrastructure as Code manifests. For instance, AWS CloudFormation templates or Terraform configurations.                                      |
```

2024-07-11 10:35 UTC, jroimartin commented on src/controls.md
> +| [vulcan-trivy](https://github.com/adevinta/vulcan-checks/tree/master/cmd/vulcan-trivy)       | Scan docker images and Git repositories using aquasec/trivy. Official Documentation: <https://aquasecu
For consistency with the previous table.

```suggestion
| [vulcan-trivy](https://github.com/adevinta/vulcan-checks/tree/master/cmd/vulcan-trivy)       | Scan docker images and Git repositories using aquasec/trivy. Official Documentation: <https://aquasecurity.github.io/trivy/latest> | SCA, IaC security, Secret detection |
```

2024-07-11 10:35 UTC, jroimartin commented on src/controls.md
> +| Checktype                                                                                                            | Description
Use the same case as in the first table (i.e. `Data analysis`, `Finding collection`, `Secret detection`).

2024-07-11 12:02 UTC, jroimartin approved these changes
LGTM

2024-07-11 12:03 UTC, merged